name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: python

  deploy-release:
    needs: release
    if: ${{ needs.release.outputs.release_created }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Authentification GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configurer Docker
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Build et push avec tag de version
        run: |
          IMAGE=europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/flask-repo/flask-app
          VERSION=${{ needs.release.outputs.tag_name }}
          SHORT_SHA=$(echo ${{ github.sha }} | cut -c1-7)
          docker build \
            -t $IMAGE:$VERSION \
            -t $IMAGE:${{ github.sha }} \
            -t $IMAGE:sha-$SHORT_SHA \
            -t $IMAGE:latest \
            .
          docker push $IMAGE:$VERSION
          docker push $IMAGE:${{ github.sha }}
          docker push $IMAGE:sha-$SHORT_SHA
          docker push $IMAGE:latest

      - name: Deployer sur Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: flask-app
          region: europe-west1
          image: europe-west1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/flask-repo/flask-app:${{ needs.release.outputs.tag_name }}
